# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '_UI_Control.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QSpacerItem, QSpinBox,
    QTabWidget, QToolBox, QVBoxLayout, QWidget)

class Ui_CONTROL(object):
    def setupUi(self, CONTROL):
        if not CONTROL.objectName():
            CONTROL.setObjectName(u"CONTROL")
        CONTROL.resize(190, 832)
        CONTROL.setMinimumSize(QSize(190, 825))
        CONTROL.setMaximumSize(QSize(190, 832))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        CONTROL.setFont(font)
        CONTROL.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.actionLoad_profiles = QAction(CONTROL)
        self.actionLoad_profiles.setObjectName(u"actionLoad_profiles")
        font1 = QFont()
        font1.setPointSize(10)
        self.actionLoad_profiles.setFont(font1)
        self.actionLoad_GeoTiff = QAction(CONTROL)
        self.actionLoad_GeoTiff.setObjectName(u"actionLoad_GeoTiff")
        self.actionLoad_GeoTiff.setFont(font1)
        self.actionLoad_tide = QAction(CONTROL)
        self.actionLoad_tide.setObjectName(u"actionLoad_tide")
        self.actionLoad_tide.setFont(font1)
        self.actionSave_work = QAction(CONTROL)
        self.actionSave_work.setObjectName(u"actionSave_work")
        self.actionSave_work.setFont(font1)
        self.actionLoad_saved_work = QAction(CONTROL)
        self.actionLoad_saved_work.setObjectName(u"actionLoad_saved_work")
        self.actionLoad_saved_work.setFont(font1)
        self.actionExport_EIVA = QAction(CONTROL)
        self.actionExport_EIVA.setObjectName(u"actionExport_EIVA")
        self.actionExport_EIVA.setFont(font1)
        self.actionLoad_pipetracker = QAction(CONTROL)
        self.actionLoad_pipetracker.setObjectName(u"actionLoad_pipetracker")
        self.actionLoad_pipetracker.setFont(font1)
        self.actionSave_layout = QAction(CONTROL)
        self.actionSave_layout.setObjectName(u"actionSave_layout")
        self.actionSave_layout.setFont(font1)
        self.actionLoad_layout = QAction(CONTROL)
        self.actionLoad_layout.setObjectName(u"actionLoad_layout")
        self.actionLoad_layout.setFont(font1)
        self.actionExport_SFX = QAction(CONTROL)
        self.actionExport_SFX.setObjectName(u"actionExport_SFX")
        self.actionExport_SFX.setFont(font1)
        self.actionBuild_Playlist = QAction(CONTROL)
        self.actionBuild_Playlist.setObjectName(u"actionBuild_Playlist")
        self.actionBuild_Playlist.setFont(font1)
        self.actionLoad_playlist = QAction(CONTROL)
        self.actionLoad_playlist.setObjectName(u"actionLoad_playlist")
        self.actionLoad_playlist.setFont(font1)
        self.actionXView = QAction(CONTROL)
        self.actionXView.setObjectName(u"actionXView")
        self.actionXView.setFont(font1)
        self.actionPView = QAction(CONTROL)
        self.actionPView.setObjectName(u"actionPView")
        self.actionPView.setFont(font1)
        self.actionLView = QAction(CONTROL)
        self.actionLView.setObjectName(u"actionLView")
        self.actionLView.setFont(font1)
        self.actionSettings = QAction(CONTROL)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionSettings.setFont(font1)
        self.actionLoad_colors = QAction(CONTROL)
        self.actionLoad_colors.setObjectName(u"actionLoad_colors")
        self.actionLoad_colors.setFont(font1)
        self.actionDV_Control = QAction(CONTROL)
        self.actionDV_Control.setObjectName(u"actionDV_Control")
        self.actionDV_Control.setFont(font1)
        self.actionInfo = QAction(CONTROL)
        self.actionInfo.setObjectName(u"actionInfo")
        self.actionInfo.setEnabled(False)
        self.actionInfo.setFont(font1)
        self.actionVersion = QAction(CONTROL)
        self.actionVersion.setObjectName(u"actionVersion")
        self.actionVersion.setCheckable(False)
        self.actionVersion.setEnabled(False)
        self.actionVersion.setFont(font1)
        self.actionManual = QAction(CONTROL)
        self.actionManual.setObjectName(u"actionManual")
        self.actionManual.setFont(font1)
        self.actionLoad_events = QAction(CONTROL)
        self.actionLoad_events.setObjectName(u"actionLoad_events")
        self.actionLoad_events.setFont(font1)
        self.actionEvents = QAction(CONTROL)
        self.actionEvents.setObjectName(u"actionEvents")
        self.actionEvents.setFont(font1)
        self.actionLicense = QAction(CONTROL)
        self.actionLicense.setObjectName(u"actionLicense")
        self.centralwidget = QWidget(CONTROL)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setMinimumSize(QSize(180, 720))
        self.tabWidget.setMaximumSize(QSize(180, 720))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.tabWidget.setFont(font2)
        self.tabPipe = QWidget()
        self.tabPipe.setObjectName(u"tabPipe")
        self.tabPipe.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.verticalLayout_4 = QVBoxLayout(self.tabPipe)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.toolBoxPipe = QToolBox(self.tabPipe)
        self.toolBoxPipe.setObjectName(u"toolBoxPipe")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBoxPipe.sizePolicy().hasHeightForWidth())
        self.toolBoxPipe.setSizePolicy(sizePolicy)
        self.toolBoxPipe.setMinimumSize(QSize(165, 242))
        self.toolBoxPipe.setMaximumSize(QSize(165, 242))
        self.toolBoxPipe.setFont(font2)
        self.toolBoxPipe.setFrameShape(QFrame.Shape.Panel)
        self.p0 = QWidget()
        self.p0.setObjectName(u"p0")
        self.p0.setGeometry(QRect(0, 0, 163, 30))
        self.p0.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.t_D = QLineEdit(self.p0)
        self.t_D.setObjectName(u"t_D")
        self.t_D.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_D.sizePolicy().hasHeightForWidth())
        self.t_D.setSizePolicy(sizePolicy)
        self.t_D.setMinimumSize(QSize(80, 30))
        self.t_D.setMaximumSize(QSize(80, 30))
        font3 = QFont()
        font3.setPointSize(14)
        font3.setBold(True)
        self.t_D.setFont(font3)
        self.t_D.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.t_D.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.t_D.setClearButtonEnabled(False)
        self.toolBoxPipe.addItem(self.p0, u"Pipe D")
        self.p1 = QWidget()
        self.p1.setObjectName(u"p1")
        self.p1.setGeometry(QRect(0, 0, 163, 30))
        self.t_IW = QLineEdit(self.p1)
        self.t_IW.setObjectName(u"t_IW")
        self.t_IW.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_IW.sizePolicy().hasHeightForWidth())
        self.t_IW.setSizePolicy(sizePolicy)
        self.t_IW.setMinimumSize(QSize(80, 30))
        self.t_IW.setMaximumSize(QSize(80, 30))
        self.t_IW.setFont(font3)
        self.t_IW.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxPipe.addItem(self.p1, u"in Wall * D")
        self.p2 = QWidget()
        self.p2.setObjectName(u"p2")
        self.p2.setGeometry(QRect(0, 0, 163, 30))
        self.t_OW = QLineEdit(self.p2)
        self.t_OW.setObjectName(u"t_OW")
        self.t_OW.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_OW.sizePolicy().hasHeightForWidth())
        self.t_OW.setSizePolicy(sizePolicy)
        self.t_OW.setMinimumSize(QSize(80, 30))
        self.t_OW.setMaximumSize(QSize(80, 30))
        self.t_OW.setFont(font3)
        self.t_OW.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxPipe.addItem(self.p2, u"out Wall * D")
        self.p3 = QWidget()
        self.p3.setObjectName(u"p3")
        self.p3.setGeometry(QRect(0, 0, 163, 30))
        self.t_HW = QLineEdit(self.p3)
        self.t_HW.setObjectName(u"t_HW")
        self.t_HW.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_HW.sizePolicy().hasHeightForWidth())
        self.t_HW.setSizePolicy(sizePolicy)
        self.t_HW.setMinimumSize(QSize(80, 30))
        self.t_HW.setMaximumSize(QSize(80, 30))
        self.t_HW.setFont(font3)
        self.t_HW.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxPipe.addItem(self.p3, u"H window")
        self.p4 = QWidget()
        self.p4.setObjectName(u"p4")
        self.p4.setGeometry(QRect(0, 0, 163, 30))
        self.t_VW = QLineEdit(self.p4)
        self.t_VW.setObjectName(u"t_VW")
        self.t_VW.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_VW.sizePolicy().hasHeightForWidth())
        self.t_VW.setSizePolicy(sizePolicy)
        self.t_VW.setMinimumSize(QSize(80, 30))
        self.t_VW.setMaximumSize(QSize(80, 30))
        self.t_VW.setFont(font3)
        self.t_VW.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxPipe.addItem(self.p4, u"V Window")
        self.p5 = QWidget()
        self.p5.setObjectName(u"p5")
        self.p5.setGeometry(QRect(0, 0, 163, 30))
        self.t_RES = QLineEdit(self.p5)
        self.t_RES.setObjectName(u"t_RES")
        self.t_RES.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_RES.sizePolicy().hasHeightForWidth())
        self.t_RES.setSizePolicy(sizePolicy)
        self.t_RES.setMinimumSize(QSize(80, 30))
        self.t_RES.setMaximumSize(QSize(80, 30))
        self.t_RES.setFont(font3)
        self.t_RES.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxPipe.addItem(self.p5, u"Resolution")
        self.p6 = QWidget()
        self.p6.setObjectName(u"p6")
        self.p6.setGeometry(QRect(0, 0, 163, 30))
        self.sp_Weed = QSpinBox(self.p6)
        self.sp_Weed.setObjectName(u"sp_Weed")
        self.sp_Weed.setGeometry(QRect(0, 0, 130, 30))
        sizePolicy.setHeightForWidth(self.sp_Weed.sizePolicy().hasHeightForWidth())
        self.sp_Weed.setSizePolicy(sizePolicy)
        self.sp_Weed.setMinimumSize(QSize(130, 30))
        self.sp_Weed.setMaximumSize(QSize(130, 30))
        self.sp_Weed.setFont(font3)
        self.sp_Weed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sp_Weed.setMinimum(1)
        self.sp_Weed.setMaximum(10)
        self.toolBoxPipe.addItem(self.p6, u"Decimate")

        self.verticalLayout_4.addWidget(self.toolBoxPipe)

        self.toolBoxFlags = QToolBox(self.tabPipe)
        self.toolBoxFlags.setObjectName(u"toolBoxFlags")
        self.toolBoxFlags.setMinimumSize(QSize(165, 182))
        self.toolBoxFlags.setMaximumSize(QSize(165, 182))
        self.toolBoxFlags.setFont(font2)
        self.toolBoxFlags.setFrameShape(QFrame.Shape.Box)
        self.f1 = QWidget()
        self.f1.setObjectName(u"f1")
        self.f1.setGeometry(QRect(0, 0, 163, 30))
        self.t_FlPt = QLineEdit(self.f1)
        self.t_FlPt.setObjectName(u"t_FlPt")
        self.t_FlPt.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_FlPt.sizePolicy().hasHeightForWidth())
        self.t_FlPt.setSizePolicy(sizePolicy)
        self.t_FlPt.setMinimumSize(QSize(80, 30))
        self.t_FlPt.setMaximumSize(QSize(80, 30))
        self.t_FlPt.setFont(font3)
        self.t_FlPt.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxFlags.addItem(self.f1, u"in Flag patch")
        self.f2 = QWidget()
        self.f2.setObjectName(u"f2")
        self.f2.setGeometry(QRect(0, 0, 163, 30))
        self.t_AdPad = QLineEdit(self.f2)
        self.t_AdPad.setObjectName(u"t_AdPad")
        self.t_AdPad.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_AdPad.sizePolicy().hasHeightForWidth())
        self.t_AdPad.setSizePolicy(sizePolicy)
        self.t_AdPad.setMinimumSize(QSize(80, 30))
        self.t_AdPad.setMaximumSize(QSize(80, 30))
        self.t_AdPad.setFont(font3)
        self.t_AdPad.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxFlags.addItem(self.f2, u"Pad")
        self.f3 = QWidget()
        self.f3.setObjectName(u"f3")
        self.f3.setGeometry(QRect(0, 0, 163, 30))
        self.t_AntiSpoof = QLineEdit(self.f3)
        self.t_AntiSpoof.setObjectName(u"t_AntiSpoof")
        self.t_AntiSpoof.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_AntiSpoof.sizePolicy().hasHeightForWidth())
        self.t_AntiSpoof.setSizePolicy(sizePolicy)
        self.t_AntiSpoof.setMinimumSize(QSize(80, 30))
        self.t_AntiSpoof.setMaximumSize(QSize(80, 30))
        self.t_AntiSpoof.setFont(font3)
        self.t_AntiSpoof.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxFlags.addItem(self.f3, u"AS Mask D")
        self.f4 = QWidget()
        self.f4.setObjectName(u"f4")
        self.f4.setGeometry(QRect(0, 0, 163, 30))
        self.t_AntiSpoof_A = QLineEdit(self.f4)
        self.t_AntiSpoof_A.setObjectName(u"t_AntiSpoof_A")
        self.t_AntiSpoof_A.setGeometry(QRect(0, 0, 80, 30))
        self.t_AntiSpoof_A.setMinimumSize(QSize(80, 30))
        self.t_AntiSpoof_A.setMaximumSize(QSize(80, 30))
        self.t_AntiSpoof_A.setFont(font3)
        self.t_AntiSpoof_A.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxFlags.addItem(self.f4, u"As Mask A")
        self.f5 = QWidget()
        self.f5.setObjectName(u"f5")
        self.f5.setGeometry(QRect(0, 0, 163, 30))
        self.t_FoDist = QLineEdit(self.f5)
        self.t_FoDist.setObjectName(u"t_FoDist")
        self.t_FoDist.setGeometry(QRect(0, 0, 80, 30))
        self.t_FoDist.setMinimumSize(QSize(80, 30))
        self.t_FoDist.setMaximumSize(QSize(80, 30))
        self.t_FoDist.setFont(font3)
        self.t_FoDist.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxFlags.addItem(self.f5, u"out Flag Dist")

        self.verticalLayout_4.addWidget(self.toolBoxFlags)

        self.gB1 = QGroupBox(self.tabPipe)
        self.gB1.setObjectName(u"gB1")
        sizePolicy.setHeightForWidth(self.gB1.sizePolicy().hasHeightForWidth())
        self.gB1.setSizePolicy(sizePolicy)
        self.gB1.setMinimumSize(QSize(165, 170))
        self.gB1.setMaximumSize(QSize(165, 170))
        self.gB1.setFont(font2)
        self.verticalLayout = QVBoxLayout(self.gB1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.rb_Fmin = QRadioButton(self.gB1)
        self.rb_Fmin.setObjectName(u"rb_Fmin")
        sizePolicy.setHeightForWidth(self.rb_Fmin.sizePolicy().hasHeightForWidth())
        self.rb_Fmin.setSizePolicy(sizePolicy)
        self.rb_Fmin.setMinimumSize(QSize(130, 20))
        self.rb_Fmin.setMaximumSize(QSize(130, 20))

        self.verticalLayout.addWidget(self.rb_Fmin)

        self.rb_Fmax = QRadioButton(self.gB1)
        self.rb_Fmax.setObjectName(u"rb_Fmax")
        sizePolicy.setHeightForWidth(self.rb_Fmax.sizePolicy().hasHeightForWidth())
        self.rb_Fmax.setSizePolicy(sizePolicy)
        self.rb_Fmax.setMinimumSize(QSize(130, 20))
        self.rb_Fmax.setMaximumSize(QSize(130, 20))

        self.verticalLayout.addWidget(self.rb_Fmax)

        self.rb_Fmean = QRadioButton(self.gB1)
        self.rb_Fmean.setObjectName(u"rb_Fmean")
        sizePolicy.setHeightForWidth(self.rb_Fmean.sizePolicy().hasHeightForWidth())
        self.rb_Fmean.setSizePolicy(sizePolicy)
        self.rb_Fmean.setMinimumSize(QSize(130, 20))
        self.rb_Fmean.setMaximumSize(QSize(130, 20))

        self.verticalLayout.addWidget(self.rb_Fmean)

        self.rb_Fadapt = QRadioButton(self.gB1)
        self.rb_Fadapt.setObjectName(u"rb_Fadapt")
        sizePolicy.setHeightForWidth(self.rb_Fadapt.sizePolicy().hasHeightForWidth())
        self.rb_Fadapt.setSizePolicy(sizePolicy)
        self.rb_Fadapt.setMinimumSize(QSize(130, 20))
        self.rb_Fadapt.setMaximumSize(QSize(130, 20))
        self.rb_Fadapt.setChecked(True)

        self.verticalLayout.addWidget(self.rb_Fadapt)

        self.line = QFrame(self.gB1)
        self.line.setObjectName(u"line")
        self.line.setMinimumSize(QSize(130, 5))
        self.line.setMaximumSize(QSize(130, 5))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.ch_FiSnap = QCheckBox(self.gB1)
        self.ch_FiSnap.setObjectName(u"ch_FiSnap")
        sizePolicy.setHeightForWidth(self.ch_FiSnap.sizePolicy().hasHeightForWidth())
        self.ch_FiSnap.setSizePolicy(sizePolicy)
        self.ch_FiSnap.setMinimumSize(QSize(130, 20))
        self.ch_FiSnap.setMaximumSize(QSize(130, 20))
        self.ch_FiSnap.setChecked(True)

        self.verticalLayout.addWidget(self.ch_FiSnap)

        self.ch_FoSnap = QCheckBox(self.gB1)
        self.ch_FoSnap.setObjectName(u"ch_FoSnap")
        self.ch_FoSnap.setMinimumSize(QSize(130, 20))
        self.ch_FoSnap.setMaximumSize(QSize(130, 20))
        self.ch_FoSnap.setChecked(True)

        self.verticalLayout.addWidget(self.ch_FoSnap)


        self.verticalLayout_4.addWidget(self.gB1)

        self.ch_ApplyTide = QCheckBox(self.tabPipe)
        self.ch_ApplyTide.setObjectName(u"ch_ApplyTide")
        self.ch_ApplyTide.setEnabled(False)
        sizePolicy.setHeightForWidth(self.ch_ApplyTide.sizePolicy().hasHeightForWidth())
        self.ch_ApplyTide.setSizePolicy(sizePolicy)
        self.ch_ApplyTide.setMinimumSize(QSize(165, 20))
        self.ch_ApplyTide.setMaximumSize(QSize(165, 20))
        self.ch_ApplyTide.setFont(font2)
        self.ch_ApplyTide.setChecked(True)

        self.verticalLayout_4.addWidget(self.ch_ApplyTide)

        self.tabWidget.addTab(self.tabPipe, "")
        self.tabPT = QWidget()
        self.tabPT.setObjectName(u"tabPT")
        self.verticalLayout_3 = QVBoxLayout(self.tabPT)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.toolBoxPtSet = QToolBox(self.tabPT)
        self.toolBoxPtSet.setObjectName(u"toolBoxPtSet")
        self.toolBoxPtSet.setMinimumSize(QSize(165, 201))
        self.toolBoxPtSet.setMaximumSize(QSize(165, 201))
        self.toolBoxPtSet.setFrameShape(QFrame.Shape.Box)
        self.pts0 = QWidget()
        self.pts0.setObjectName(u"pts0")
        self.pts0.setGeometry(QRect(0, 0, 163, 75))
        self.sp_Pt_Weed = QSpinBox(self.pts0)
        self.sp_Pt_Weed.setObjectName(u"sp_Pt_Weed")
        self.sp_Pt_Weed.setEnabled(False)
        self.sp_Pt_Weed.setGeometry(QRect(0, 0, 130, 30))
        self.sp_Pt_Weed.setMinimumSize(QSize(130, 30))
        self.sp_Pt_Weed.setMaximumSize(QSize(130, 30))
        self.sp_Pt_Weed.setFont(font3)
        self.sp_Pt_Weed.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.sp_Pt_Weed.setMinimum(1)
        self.sp_Pt_Weed.setMaximum(1000)
        self.sp_Pt_Weed.setValue(1)
        self.toolBoxPtSet.addItem(self.pts0, u"Decimate")
        self.pts1 = QWidget()
        self.pts1.setObjectName(u"pts1")
        self.pts1.setGeometry(QRect(0, 0, 96, 26))
        self.t_PtGap = QLineEdit(self.pts1)
        self.t_PtGap.setObjectName(u"t_PtGap")
        self.t_PtGap.setEnabled(False)
        self.t_PtGap.setGeometry(QRect(0, 0, 80, 30))
        sizePolicy.setHeightForWidth(self.t_PtGap.sizePolicy().hasHeightForWidth())
        self.t_PtGap.setSizePolicy(sizePolicy)
        self.t_PtGap.setMinimumSize(QSize(80, 30))
        self.t_PtGap.setMaximumSize(QSize(80, 30))
        self.t_PtGap.setFont(font3)
        self.t_PtGap.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxPtSet.addItem(self.pts1, u"Max gap")
        self.pts2 = QWidget()
        self.pts2.setObjectName(u"pts2")
        self.pts2.setGeometry(QRect(0, 0, 96, 26))
        self.l2 = QLabel(self.pts2)
        self.l2.setObjectName(u"l2")
        self.l2.setGeometry(QRect(10, 0, 60, 30))
        self.l2.setMinimumSize(QSize(60, 30))
        self.l2.setMaximumSize(QSize(60, 30))
        self.l2.setFont(font2)
        self.l2.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.t_smW = QLineEdit(self.pts2)
        self.t_smW.setObjectName(u"t_smW")
        self.t_smW.setEnabled(False)
        self.t_smW.setGeometry(QRect(70, 0, 80, 30))
        self.t_smW.setMinimumSize(QSize(80, 30))
        self.t_smW.setMaximumSize(QSize(80, 30))
        self.t_smW.setFont(font3)
        self.t_smW.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.b_smoothPT_p_MA = QPushButton(self.pts2)
        self.b_smoothPT_p_MA.setObjectName(u"b_smoothPT_p_MA")
        self.b_smoothPT_p_MA.setEnabled(False)
        self.b_smoothPT_p_MA.setGeometry(QRect(0, 35, 75, 40))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.b_smoothPT_p_MA.sizePolicy().hasHeightForWidth())
        self.b_smoothPT_p_MA.setSizePolicy(sizePolicy1)
        self.b_smoothPT_p_MA.setMinimumSize(QSize(75, 40))
        self.b_smoothPT_p_MA.setMaximumSize(QSize(75, 40))
        self.b_smoothPT_p_MA.setFont(font3)
        self.b_smoothPT_p_MA.setFlat(False)
        self.b_smoothPT_l_MA = QPushButton(self.pts2)
        self.b_smoothPT_l_MA.setObjectName(u"b_smoothPT_l_MA")
        self.b_smoothPT_l_MA.setEnabled(False)
        self.b_smoothPT_l_MA.setGeometry(QRect(75, 35, 75, 40))
        self.b_smoothPT_l_MA.setMinimumSize(QSize(75, 40))
        self.b_smoothPT_l_MA.setMaximumSize(QSize(75, 40))
        self.b_smoothPT_l_MA.setFont(font3)
        self.toolBoxPtSet.addItem(self.pts2, u"Smooth")
        self.pts3 = QWidget()
        self.pts3.setObjectName(u"pts3")
        self.pts3.setGeometry(QRect(0, 0, 96, 26))
        self.t_Lev = QLineEdit(self.pts3)
        self.t_Lev.setObjectName(u"t_Lev")
        self.t_Lev.setEnabled(False)
        self.t_Lev.setGeometry(QRect(0, 0, 80, 30))
        self.t_Lev.setMinimumSize(QSize(80, 30))
        self.t_Lev.setMaximumSize(QSize(80, 30))
        self.t_Lev.setFont(font3)
        self.t_Lev.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.b_levelPT = QPushButton(self.pts3)
        self.b_levelPT.setObjectName(u"b_levelPT")
        self.b_levelPT.setEnabled(False)
        self.b_levelPT.setGeometry(QRect(0, 30, 75, 40))
        self.b_levelPT.setMinimumSize(QSize(75, 40))
        self.b_levelPT.setMaximumSize(QSize(75, 40))
        self.b_levelPT.setFont(font3)
        self.toolBoxPtSet.addItem(self.pts3, u"Level")

        self.verticalLayout_3.addWidget(self.toolBoxPtSet)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.b_analysePtShift = QPushButton(self.tabPT)
        self.b_analysePtShift.setObjectName(u"b_analysePtShift")
        self.b_analysePtShift.setEnabled(False)
        self.b_analysePtShift.setMinimumSize(QSize(120, 40))
        self.b_analysePtShift.setMaximumSize(QSize(120, 40))

        self.horizontalLayout.addWidget(self.b_analysePtShift)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)


        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_3)

        self.b_savePT = QPushButton(self.tabPT)
        self.b_savePT.setObjectName(u"b_savePT")
        self.b_savePT.setEnabled(False)
        self.b_savePT.setMinimumSize(QSize(120, 40))
        self.b_savePT.setMaximumSize(QSize(120, 40))
        self.b_savePT.setFont(font3)

        self.horizontalLayout_2.addWidget(self.b_savePT)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_4)


        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_3.addItem(self.verticalSpacer)

        self.tabWidget.addTab(self.tabPT, "")
        self.tabDV = QWidget()
        self.tabDV.setObjectName(u"tabDV")
        self.verticalLayout_7 = QVBoxLayout(self.tabDV)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.toolBoxVideo = QToolBox(self.tabDV)
        self.toolBoxVideo.setObjectName(u"toolBoxVideo")
        self.toolBoxVideo.setMinimumSize(QSize(165, 125))
        self.toolBoxVideo.setMaximumSize(QSize(165, 125))
        self.toolBoxVideo.setFrameShape(QFrame.Shape.Box)
        self.v1 = QWidget()
        self.v1.setObjectName(u"v1")
        self.v1.setGeometry(QRect(0, 0, 163, 30))
        self.spb_Timezone = QDoubleSpinBox(self.v1)
        self.spb_Timezone.setObjectName(u"spb_Timezone")
        self.spb_Timezone.setGeometry(QRect(0, 0, 130, 30))
        self.spb_Timezone.setMinimumSize(QSize(130, 30))
        self.spb_Timezone.setMaximumSize(QSize(130, 30))
        self.spb_Timezone.setFont(font3)
        self.spb_Timezone.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spb_Timezone.setDecimals(1)
        self.spb_Timezone.setMinimum(-12.000000000000000)
        self.spb_Timezone.setMaximum(12.000000000000000)
        self.spb_Timezone.setSingleStep(0.500000000000000)
        self.toolBoxVideo.addItem(self.v1, u"Time Zone")
        self.v2 = QWidget()
        self.v2.setObjectName(u"v2")
        self.v2.setGeometry(QRect(0, 0, 96, 26))
        self.t_CamOffset = QLineEdit(self.v2)
        self.t_CamOffset.setObjectName(u"t_CamOffset")
        self.t_CamOffset.setEnabled(True)
        self.t_CamOffset.setGeometry(QRect(0, 0, 80, 30))
        self.t_CamOffset.setMinimumSize(QSize(80, 30))
        self.t_CamOffset.setMaximumSize(QSize(80, 30))
        self.t_CamOffset.setFont(font3)
        self.t_CamOffset.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.toolBoxVideo.addItem(self.v2, u"Cam offset")
        self.v3 = QWidget()
        self.v3.setObjectName(u"v3")
        self.v3.setGeometry(QRect(0, 0, 138, 30))
        self.spb_CamSize = QSpinBox(self.v3)
        self.spb_CamSize.setObjectName(u"spb_CamSize")
        self.spb_CamSize.setGeometry(QRect(0, 0, 130, 30))
        self.spb_CamSize.setMinimumSize(QSize(130, 30))
        self.spb_CamSize.setMaximumSize(QSize(130, 30))
        self.spb_CamSize.setFont(font3)
        self.spb_CamSize.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spb_CamSize.setMinimum(4)
        self.spb_CamSize.setMaximum(50)
        self.spb_CamSize.setValue(15)
        self.toolBoxVideo.addItem(self.v3, u"Symbol size")

        self.verticalLayout_7.addWidget(self.toolBoxVideo)

        self.ch_ShowCamOffset = QCheckBox(self.tabDV)
        self.ch_ShowCamOffset.setObjectName(u"ch_ShowCamOffset")
        self.ch_ShowCamOffset.setMinimumSize(QSize(165, 20))
        self.ch_ShowCamOffset.setMaximumSize(QSize(165, 20))
        self.ch_ShowCamOffset.setChecked(True)

        self.verticalLayout_7.addWidget(self.ch_ShowCamOffset)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_7.addItem(self.verticalSpacer_3)

        self.tabWidget.addTab(self.tabDV, "")

        self.verticalLayout_2.addWidget(self.tabWidget)

        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setMinimumSize(QSize(180, 3))
        self.line_3.setMaximumSize(QSize(180, 3))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_2.addWidget(self.line_3)

        self.l_Coord = QLabel(self.centralwidget)
        self.l_Coord.setObjectName(u"l_Coord")
        self.l_Coord.setMinimumSize(QSize(180, 20))
        self.l_Coord.setMaximumSize(QSize(180, 20))
        self.l_Coord.setFont(font2)

        self.verticalLayout_2.addWidget(self.l_Coord)

        self.l_Saved = QLabel(self.centralwidget)
        self.l_Saved.setObjectName(u"l_Saved")
        self.l_Saved.setMinimumSize(QSize(180, 20))
        self.l_Saved.setMaximumSize(QSize(180, 20))
        self.l_Saved.setFont(font2)

        self.verticalLayout_2.addWidget(self.l_Saved)

        CONTROL.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(CONTROL)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 190, 33))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setFont(font)
        CONTROL.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menuFile.addAction(self.actionLoad_profiles)
        self.menuFile.addAction(self.actionLoad_GeoTiff)
        self.menuFile.addAction(self.actionLoad_tide)
        self.menuFile.addAction(self.actionLoad_pipetracker)
        self.menuFile.addAction(self.actionLoad_saved_work)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_work)
        self.menuFile.addAction(self.actionExport_EIVA)
        self.menuFile.addAction(self.actionExport_SFX)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionBuild_Playlist)
        self.menuFile.addAction(self.actionLoad_playlist)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionXView)
        self.menuFile.addAction(self.actionPView)
        self.menuFile.addAction(self.actionLView)
        self.menuFile.addAction(self.actionDV_Control)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionManual)
        self.menuFile.addAction(self.actionLicense)

        self.retranslateUi(CONTROL)
        self.t_IW.editingFinished.connect(CONTROL.setFocus)
        self.t_HW.editingFinished.connect(CONTROL.setFocus)
        self.t_D.editingFinished.connect(CONTROL.setFocus)
        self.t_FlPt.editingFinished.connect(CONTROL.setFocus)
        self.t_AdPad.editingFinished.connect(CONTROL.setFocus)
        self.t_VW.editingFinished.connect(CONTROL.setFocus)
        self.ch_ApplyTide.stateChanged.connect(CONTROL.setFocus)
        self.t_FoDist.editingFinished.connect(CONTROL.setFocus)
        self.gB1.toggled.connect(CONTROL.setFocus)
        self.ch_FiSnap.stateChanged.connect(CONTROL.setFocus)
        self.t_RES.editingFinished.connect(CONTROL.setFocus)
        self.t_OW.editingFinished.connect(CONTROL.setFocus)
        self.t_AntiSpoof.editingFinished.connect(CONTROL.setFocus)
        self.ch_FoSnap.stateChanged.connect(CONTROL.setFocus)

        self.tabWidget.setCurrentIndex(0)
        self.toolBoxPipe.setCurrentIndex(0)
        self.toolBoxPipe.layout().setSpacing(5)
        self.toolBoxFlags.setCurrentIndex(0)
        self.toolBoxFlags.layout().setSpacing(5)
        self.toolBoxPtSet.setCurrentIndex(0)
        self.toolBoxVideo.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(CONTROL)
    # setupUi

    def retranslateUi(self, CONTROL):
        CONTROL.setWindowTitle(QCoreApplication.translate("CONTROL", u"jP3", None))
        self.actionLoad_profiles.setText(QCoreApplication.translate("CONTROL", u"Load profiles", None))
        self.actionLoad_GeoTiff.setText(QCoreApplication.translate("CONTROL", u"Load geoimage", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_GeoTiff.setToolTip(QCoreApplication.translate("CONTROL", u"Load Georeferenced Image", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad_tide.setText(QCoreApplication.translate("CONTROL", u"Load tide", None))
        self.actionSave_work.setText(QCoreApplication.translate("CONTROL", u"Save work", None))
        self.actionLoad_saved_work.setText(QCoreApplication.translate("CONTROL", u"Load saved work", None))
        self.actionExport_EIVA.setText(QCoreApplication.translate("CONTROL", u"Export EIVA", None))
        self.actionLoad_pipetracker.setText(QCoreApplication.translate("CONTROL", u"Load pipetracker", None))
        self.actionSave_layout.setText(QCoreApplication.translate("CONTROL", u"Save workspace", None))
        self.actionLoad_layout.setText(QCoreApplication.translate("CONTROL", u"Load workspace", None))
        self.actionExport_SFX.setText(QCoreApplication.translate("CONTROL", u"Export SFX", None))
        self.actionBuild_Playlist.setText(QCoreApplication.translate("CONTROL", u"Build DV index", None))
#if QT_CONFIG(tooltip)
        self.actionBuild_Playlist.setToolTip(QCoreApplication.translate("CONTROL", u"Build DV index", None))
#endif // QT_CONFIG(tooltip)
        self.actionLoad_playlist.setText(QCoreApplication.translate("CONTROL", u"Load DV index", None))
        self.actionLoad_playlist.setIconText(QCoreApplication.translate("CONTROL", u"Load DV index", None))
#if QT_CONFIG(tooltip)
        self.actionLoad_playlist.setToolTip(QCoreApplication.translate("CONTROL", u"Load DV index", None))
#endif // QT_CONFIG(tooltip)
        self.actionXView.setText(QCoreApplication.translate("CONTROL", u"XView", None))
        self.actionPView.setText(QCoreApplication.translate("CONTROL", u"PView", None))
        self.actionLView.setText(QCoreApplication.translate("CONTROL", u"LView", None))
        self.actionSettings.setText(QCoreApplication.translate("CONTROL", u"Edit palette", None))
        self.actionLoad_colors.setText(QCoreApplication.translate("CONTROL", u"Load palette", None))
        self.actionDV_Control.setText(QCoreApplication.translate("CONTROL", u"DV Control", None))
        self.actionInfo.setText(QCoreApplication.translate("CONTROL", u"Copyright (c) 2026 Aleksandr Kaiurin (akayurin@gmail.com)", None))
        self.actionInfo.setIconText(QCoreApplication.translate("CONTROL", u"Copyright (c) 2026 Aleksandr Kaiurin (akayurin@gmail.com)", None))
        self.actionVersion.setText(QCoreApplication.translate("CONTROL", u"Version 2.1", None))
        self.actionManual.setText(QCoreApplication.translate("CONTROL", u"Manual", None))
        self.actionLoad_events.setText(QCoreApplication.translate("CONTROL", u"Load VW events", None))
        self.actionEvents.setText(QCoreApplication.translate("CONTROL", u"Events", None))
        self.actionLicense.setText(QCoreApplication.translate("CONTROL", u"License", None))
        self.t_D.setText(QCoreApplication.translate("CONTROL", u"0.2", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p0), QCoreApplication.translate("CONTROL", u"Pipe D", None))
        self.t_IW.setText(QCoreApplication.translate("CONTROL", u"0.98", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p1), QCoreApplication.translate("CONTROL", u"in Wall * D", None))
        self.t_OW.setText(QCoreApplication.translate("CONTROL", u"1.05", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p2), QCoreApplication.translate("CONTROL", u"out Wall * D", None))
        self.t_HW.setText(QCoreApplication.translate("CONTROL", u"1.0", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p3), QCoreApplication.translate("CONTROL", u"H window", None))
        self.t_VW.setText(QCoreApplication.translate("CONTROL", u"0.1", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p4), QCoreApplication.translate("CONTROL", u"V Window", None))
        self.t_RES.setText(QCoreApplication.translate("CONTROL", u"0.01", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p5), QCoreApplication.translate("CONTROL", u"Resolution", None))
        self.toolBoxPipe.setItemText(self.toolBoxPipe.indexOf(self.p6), QCoreApplication.translate("CONTROL", u"Decimate", None))
        self.t_FlPt.setText(QCoreApplication.translate("CONTROL", u"0.1", None))
        self.toolBoxFlags.setItemText(self.toolBoxFlags.indexOf(self.f1), QCoreApplication.translate("CONTROL", u"in Flag patch", None))
        self.t_AdPad.setText(QCoreApplication.translate("CONTROL", u"0.0", None))
        self.toolBoxFlags.setItemText(self.toolBoxFlags.indexOf(self.f2), QCoreApplication.translate("CONTROL", u"Pad", None))
        self.t_AntiSpoof.setText(QCoreApplication.translate("CONTROL", u"0.01", None))
        self.toolBoxFlags.setItemText(self.toolBoxFlags.indexOf(self.f3), QCoreApplication.translate("CONTROL", u"AS Mask D", None))
        self.t_AntiSpoof_A.setText(QCoreApplication.translate("CONTROL", u"45", None))
        self.toolBoxFlags.setItemText(self.toolBoxFlags.indexOf(self.f4), QCoreApplication.translate("CONTROL", u"As Mask A", None))
        self.t_FoDist.setText(QCoreApplication.translate("CONTROL", u"3", None))
        self.toolBoxFlags.setItemText(self.toolBoxFlags.indexOf(self.f5), QCoreApplication.translate("CONTROL", u"out Flag Dist", None))
        self.gB1.setTitle(QCoreApplication.translate("CONTROL", u"Flags", None))
        self.rb_Fmin.setText(QCoreApplication.translate("CONTROL", u"Minimum", None))
        self.rb_Fmax.setText(QCoreApplication.translate("CONTROL", u"Maximum", None))
        self.rb_Fmean.setText(QCoreApplication.translate("CONTROL", u"Mean", None))
        self.rb_Fadapt.setText(QCoreApplication.translate("CONTROL", u"Adaptive", None))
        self.ch_FiSnap.setText(QCoreApplication.translate("CONTROL", u"in Snap to data", None))
        self.ch_FoSnap.setText(QCoreApplication.translate("CONTROL", u"out Snap to data", None))
        self.ch_ApplyTide.setText(QCoreApplication.translate("CONTROL", u"Apply tide", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPipe), QCoreApplication.translate("CONTROL", u"Pipe", None))
        self.toolBoxPtSet.setItemText(self.toolBoxPtSet.indexOf(self.pts0), QCoreApplication.translate("CONTROL", u"Decimate", None))
        self.t_PtGap.setText(QCoreApplication.translate("CONTROL", u"5", None))
        self.toolBoxPtSet.setItemText(self.toolBoxPtSet.indexOf(self.pts1), QCoreApplication.translate("CONTROL", u"Max gap", None))
        self.l2.setText(QCoreApplication.translate("CONTROL", u"Window:", None))
        self.t_smW.setText(QCoreApplication.translate("CONTROL", u"10", None))
        self.b_smoothPT_p_MA.setText(QCoreApplication.translate("CONTROL", u"Sm", None))
        self.b_smoothPT_l_MA.setText(QCoreApplication.translate("CONTROL", u"SmZ", None))
        self.toolBoxPtSet.setItemText(self.toolBoxPtSet.indexOf(self.pts2), QCoreApplication.translate("CONTROL", u"Smooth", None))
        self.t_Lev.setText(QCoreApplication.translate("CONTROL", u"0.0", None))
        self.b_levelPT.setText(QCoreApplication.translate("CONTROL", u"L", None))
        self.toolBoxPtSet.setItemText(self.toolBoxPtSet.indexOf(self.pts3), QCoreApplication.translate("CONTROL", u"Level", None))
        self.b_analysePtShift.setText("")
        self.b_savePT.setText(QCoreApplication.translate("CONTROL", u"Save PT", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPT), QCoreApplication.translate("CONTROL", u"PT", None))
        self.toolBoxVideo.setItemText(self.toolBoxVideo.indexOf(self.v1), QCoreApplication.translate("CONTROL", u"Time Zone", None))
        self.t_CamOffset.setText(QCoreApplication.translate("CONTROL", u"0.0", None))
        self.toolBoxVideo.setItemText(self.toolBoxVideo.indexOf(self.v2), QCoreApplication.translate("CONTROL", u"Cam offset", None))
        self.toolBoxVideo.setItemText(self.toolBoxVideo.indexOf(self.v3), QCoreApplication.translate("CONTROL", u"Symbol size", None))
        self.ch_ShowCamOffset.setText(QCoreApplication.translate("CONTROL", u"Show camera", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDV), QCoreApplication.translate("CONTROL", u"Video", None))
        self.l_Coord.setText(QCoreApplication.translate("CONTROL", u"C:", None))
        self.l_Saved.setText(QCoreApplication.translate("CONTROL", u"SAVED:", None))
        self.menuFile.setTitle(QCoreApplication.translate("CONTROL", u"Menu", None))
    # retranslateUi

